steam_analytics:
  target: prod
  outputs:
    prod:
      type: postgres
      host: aws-1-us-east-2.pooler.supabase.com
      user: postgres.guuqraawfovgcnvdzxxc
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5432
      dbname: postgres
      schema: transform
      threads: 4